### ISSUE TITLE
Issue with Wealthica dev addon

### ISSUE THREAD

**Issue by mani-coder** [wealthica/wealthica.js#29]
There seems to be some issue with the wealthica.js library in the dev-addon. The update callback isn't working and breaking stuffs. 

![Untitled](https://user-images.githubusercontent.com/11651746/56858382-c3be8a80-692d-11e9-99a4-65a4287fe8ef.gif)

Loading works fine but updates aren't working properly. Please look at the issue in the above gif -- tried it with the example add-on.

**Comment by siboulet** [comment]
Thanks for reporting! There was a problem with filtering on the Developer add-on side. This issue has been resolved on our end and filtering should now work. Thank you!
