### ISSUE TITLE
Save Transaction w/o Modal

### ISSUE THREAD

**Issue by zahin-mohammad** [wealthica/wealthica.js#56]
Is there currently a way to save transactions without a modal? For some context, I'd like to implement a way to sync my transactions from [newton](https://www.newton.co/).

**Comment by oleg-vysotsky** [comment]
@zahin-mohammad yes, you can use POST /transactions endpoint:
```
const body = {
    ...
};

addon.request({
      method: “POST”,
      endpoint: `transactions`,
      {},
    });
```
